name: Build

on:
  pull_request:
    paths:
      - '**.swift'

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: 🔨 Build
        run: |
          sudo xcode-select -s /Applications/Xcode_14.2.app/
          swift build